[project]
name = "flow-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "numpy",
    "matplotlib",
    "torchdiffeq",
    "scikit-learn",
    "tqdm",
    "zstandard",
    "torchvision",
    "torchmetrics[image]",
    "scipy",
    "pandas",
    "requests",
]
# 1. 定义 PyTorch 的官方 CUDA 仓库 (这里以 CUDA 12.1 为例)
[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

# 2. 强制指定 torch 相关库去上面定义的仓库下载
[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
# 如果你用了 torchaudio，也要加上：
# torchaudio = { index = "pytorch-cu128" }